### ISSUE TITLE
nginx real_ip addition

### ISSUE THREAD

**Issue by jrynyt** [cloudendpoints/endpoints-tools#12]
Hi,

Sorry if I'm misunderstanding, but I'm wondering if [this change](https://github.com/cloudendpoints/endpoints-tools/pull/6/files) adding real_ip to the ESP nginx config was as intended.

The commit message says "Added default options of ngx_http_realip_module," but those are not the default values for those options.

The result is that any client of the ESP and any inline proxies are "trusted" to provide accurate `x-forwarded-for`, which will replace `$remote_addr` in nginx. This header is easily spoofed.

I'm not totally sure the `endpoints` nignx module uses `$remote_addr`, but I assume so in implementing IP address restrictions on API keys.

thanks.

**Comment by qiwzhang** [comment]
Thanks for raising this issue.  The change was to support api-key ip restriction.  We will do some study to see how to address this issue.

**Comment by jrynyt** [comment]
got it, thanks. I don't think there is any safe way to enforce api key ip restrictions if the ESP is behind one or more proxies -- see https://serverfault.com/questions/314574/nginx-real-ip-header-and-x-forwarded-for-seems-wrong.

You can whitelist the cidrs of trusted proxy servers via `set_real_ip_from`, then trust the rightmost non-trusted IP in x-forwarded-for as a real client/proxy IP. But if you set it to `0.0.0.0/0`, you've trusted everyone, which mean the security is useless.

Since a generic ESP can't know the environment it's running in, I don't think there's anything you can do about this.

**Comment by qiwzhang** [comment]
Our current plan is to provide a flag  --xff_trusted_proxy_list for users to set  "set_real_ip_from" in nginx config.

**Comment by qiwzhang** [comment]
It was fixed in

https://github.com/cloudendpoints/endpoints-tools/commit/a17714a68dc6721c6d8162f8d444260b505bb34e#diff-7ae980f4ba90cf09e964a1c287acb10c
