### ISSUE TITLE
Fetching the service configuration from the service management service fails

### ISSUE THREAD

**Issue by jackwootton** [cloudendpoints/endpoints-tools#29]
Following [Running a Local Extensible Service Proxy](https://cloud.google.com/endpoints/docs/openapi/running-esp-localdev), the ESP fails to fetch the service configuration from the service management service

```
INFO:Failed to fetch service config rollout strategy from the metadata server: http://169.254.169.254/computeMetadata/v1/instance/attributes/endpoints-rollout-strategy
INFO:Fetching the service configuration from the service management service
```

The actual attempt to fetch the service config rollout strategy is made in [fetch_service_config.py](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/fetch_service_config.py#L45)

```
def fetch_service_config_rollout_strategy(metadata):
    """Fetch service config rollout strategy from metadata URL."""
    url = metadata + _METADATA_PATH + "/attributes/" + \
        _METADATA_ROLLOUT_STRATEGY
    headers = {"Metadata-Flavor": "Google"}
    client = urllib3.PoolManager(ca_certs=certifi.where())
    try:
        response = client.request("GET", url, headers=headers)
    except:
        logging.info("Failed to fetch service config rollout strategy " + \
            "from the metadata server: " + url);
        return None
    status_code = response.status

    if status_code != 200:
        # Fetching rollout strategy is optional. No need to leave log
        return None

    rollout_strategy = response.data
    logging.info("Service config rollout strategy: " + rollout_strategy)
    return rollout_strategy
```

The ESP does start, but it takes ~5 minutes attempting to load the service config rollout strategy:

```
INFO:Fetching the service config rollout strategy from the metadata service

WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70ceca6590>: Failed to establish a new connection: [Errno 111] Connection refused',)': /computeMetadata/v1/instance/attributes/endpoints-rollout-strategy

WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70cecb5210>: Failed to establish a new connection: [Errno 111] Connection refused',)': /computeMetadata/v1/instance/attributes/endpoints-rollout-strategy

WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70cecb5590>: Failed to establish a new connection: [Errno 111] Connection refused',)': /computeMetadata/v1/instance/attributes/endpoints-rollout-strategy
```

This makes it almost impractical to run the ESP locally.  Docker info:

Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 22
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 39
 System Time: 2017-09-18T15:36:51.113440537Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by qiwzhang** [comment]
Fixed in
https://github.com/cloudendpoints/endpoints-tools/pull/30
