### ISSUE TITLE
ESP Bridge Networking fails with Name

### ISSUE THREAD

**Issue by jackwootton** [cloudendpoints/endpoints-tools#31]
I'm running the ESP Docker image `gcr.io/endpoints-release/endpoints-runtime:1` - which trans-codes HTTP/JSON to gRPC as per https://cloud.google.com/endpoints/docs/grpc/transcoding.

To keep things simple the gRPC service runs on port `8081` and is also exposed on `8081` (note the `--name server`)

```
docker build -t img -f ./Dockerfile ./
docker run -p 8081:8081 -d --name=server gcr.io/my-project/img:prod
```

Inside the server, there's standard code to start the gRPC server (on port `8081`)

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    # ... omitted for clarity.
    server.add_insecure_port('[::]:8081')
    server.start()

I have the standard Docker networks (`docker network ls`):

```
NETWORK ID          NAME                DRIVER              SCOPE
560e907ecd1e        bridge              bridge              local               
884ba3f285e0        host                host                local               
04f9dca15f84        none                null                local  
```

To check things are OK from a networking perspective, I inspect the `bridge` network and see my `server` container listed:

```
"Containers": {
  "7f4f119b83661762b9a65d49315131798d47bcf0830c1b5222bb50f1b677ab11": {
    "Name": "server",
    "EndpointID": "b9765ceb5f5edf4a63d7d06aa0e61a5481802a6dad41fe26520e3180512ab777",
    "MacAddress": "02:42:c0:a8:09:02",
    "IPv4Address": "192.168.9.2/24",
    "IPv6Address": ""
  }
}
```

Next I start the [Local Extensible Service Proxy](https://cloud.google.com/endpoints/docs/openapi/running-esp-localdev) container with a host port `80` and container port `8080`:

```
docker run -p 80:8080 -d \
--name esp -v ~/Downloads:/esp -t gcr.io/endpoints-release/endpoints-runtime:1 \
--service=jsonschema.endpoints.json-schema.cloud.goog --version=2017-09-20r7 \
--backend=grpc://server:8081 -k /esp/serviceaccount.json --rollout_strategy fixed
```

The `--backend` is passed into the [ESP start-up script](endpoints-tools/start_esp/start_esp.py), as `grpc://server:8081`. I'm following the documentation at [Running the sample API and ESP in a Docker container](https://cloud.google.com/endpoints/docs/grpc/get-started-grpc-compute-engine-docker#running_the_sample_api_and_esp_in_a_docker_container).

Again, checking the `bridge` network, I see both containers attached (`docker network inspect bridge`):

```
"Containers": {
  "0f7e1aff29d91240d6315e90acb21328ea290a7d11695a035a23ac9d23b7612e": {
      "Name": "esp",
      "EndpointID": "138ac5bfe7e18a36482d2338345aada189a1b8df651481f8ddc13535a70db2c0",
      "MacAddress": "02:42:c0:a8:09:03",
      "IPv4Address": "192.168.9.3/24",
      "IPv6Address": ""
  },
  "7f4f119b83661762b9a65d49315131798d47bcf0830c1b5222bb50f1b677ab11": {
      "Name": "server",
      "EndpointID": "b9765ceb5f5edf4a63d7d06aa0e61a5481802a6dad41fe26520e3180512ab777",
      "MacAddress": "02:42:c0:a8:09:02",
      "IPv4Address": "192.168.9.2/24",
      "IPv6Address": ""
  }
}
```

This all looks good. However, the two containers fail to communicate. Both are running - checked by hitting the ESP with `curl localhost:80`, and calling my API directly with `curl localhost:8081`.

If however, I specify the **IP address** of the server when starting the ESP, the containers communicate and the ESP successfully trans-codes HTTP/JSON to gRPC and back again:

```
docker run -p 80:8080 -d \
--name esp -v ~/Downloads:/esp -t gcr.io/endpoints-release/endpoints-runtime:1 \
--service=jsonschema.endpoints.json-schema.cloud.goog --version=2017-09-20r7 \
--backend=grpc://192.168.9.2:8081 -k /esp/serviceaccount.json --rollout_strategy fixed
```

Note the `--backend` flag takes the value reported from `docker network inspect bridge`:

`--backend=grpc://192.168.9.2:8081`

As I said, this works - but surely using a name should too? Is this a problem in endpoints-[tools/start_esp/start_esp.py](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py) perhaps?

Looking at [tools/start_esp/start_esp.py](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py) the `--backend` argument has a default of `127.0.0.1:8081`

    ```
    # Default backend
    DEFAULT_BACKEND = "127.0.0.1:8081"

    # ... Omitted for brevity

    parser.add_argument('-a', '--backend', default=DEFAULT_BACKEND, help='''
    Change the application server address to which ESP proxies the requests.
    Default value: {backend}. For HTTPS backends, please use "https://" prefix,
    e.g. https://127.0.0.1:8081. For HTTP/1.x backends, prefix "http://" is
    optional. For GRPC backends, please use "grpc://" prefix,
    e.g. grpc://127.0.0.1:8081.'''.format(backend=DEFAULT_BACKEND))
    ```

...hence why I used 8081 for both the host port and container port of my gRPC service. However, I can't make use of the default for `--backend` because I must specify the `grpc://` protocol.  Not a big deal, but the containers still fail to communicate.

I checked `/etc/nginx/endpoints/nginx.conf` on my ESP running locally to look at the effective nginx configuration. Here's the server block with the location using `localhost:8081` 

  ```
server {
    server_name "";

    listen 8080 backlog=16384;

    access_log /dev/stdout;


    location / {
      # Begin Endpoints v2 Support
      endpoints {
        on;
        server_config /etc/nginx/server_config.pb.txt;
        google_authentication_secret /esp/serviceaccount.json;
      }
      # End Endpoints v2 Support

      # WARNING: only first backend is used
      grpc_pass localhost:8081 override;
    }

    include /var/lib/nginx/extra/*.conf;
  }
```

**Comment by qiwzhang** [comment]
"server" should be in your DNS name if you use 

"--backend=grpc://server:8081". 

 In nginx config, it will be:

 grpc_pass server:8081 override;

 ESP Nginx code is doing a DNS lookup of "server".

**Comment by jackwootton** [comment]
So [endpoints-tools/start_esp/start_esp.py](https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py) defines a default for the backend:

```
# Default backend
DEFAULT_BACKEND = "127.0.0.1:8081"
```

However, the ESP Docker container will always reference it's own `localhost` (within the Docker container), and not the host's `localhost`?  The only way a `--backend` default of `128.0.0.1:8081` is useful is when running Docker containers with `--net host` ([Docker Networking](https://docs.docker.com/engine/userguide/networking/#default-networks)):

> The host network adds a container on the host’s network stack. As far as the network is concerned, there is no isolation between the host machine and the container. For instance, if you run a container that runs a web server on port 80 using host networking, the web server is available on port 80 of the host machine.

However using `--net host` would expose the gRPC service to the outside world - which kind of makes the ESP pointless in terms of security.

Using IP addresses directly means I need to redeploy the ESP container every time I make a change to my gRPC service and restart its Docker container.

Regarding DNS - I assume this refers to [Configuring DNS for Endpoints](https://cloud.google.com/endpoints/docs/openapi/get-started-compute-engine-docker#configuring-endpoints-dns)? If so, that guides uses openapi.yaml to configure endpoints. However [Deploying a gRPC API](https://cloud.google.com/endpoints/docs/grpc/deploy_grpc_api) uses Proto Descriptors with a api_confg.yaml file:

`gcloud service-management deploy out.pb api_config.yaml`

The api_config.yaml file doesn't permit syntax for configuring DNS for Endpoints. It only defines the gRPC API configuration for the gRPC Service.

I'm following the [Cloud Endpoints Architecture](https://cloud.google.com/endpoints/docs/openapi/architecture-overview) where the ESP container and gRPC Service container run on the same Compute Engine instance.

[Endpoints Getting Started with gRPC & Python Quickstart](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started-grpc), looks helpful...it deploys the service configuration using the proto descriptor and app_config.yaml

```
gcloud service-management deploy out.pb api_config.yaml
# The Config ID should be printed out, looks like: 2017-02-01r0, remember this
```

However when it comes to deploying the ESP, the URL is `grpc://grpc-hello:50051`:

```
docker run --detach --name=esp \
    -p 80:9000 \
    --link=grpc-hello:grpc-hello \
    gcr.io/endpoints-release/endpoints-runtime:1 \
    -s ${SERVICE_NAME} \
    -v ${SERVICE_CONFIG_ID} \
    -P 9000 \
    -a grpc://grpc-hello:50051
```

...there is no mention of when or how the gRPC service container was configured with this name.

**Comment by qiwzhang** [comment]
You missed "--link" flag.   You should add

--link=server:server 

when you "docker run" ESP.  and  use  "-a grpc://server:8081" for backend.

**Comment by jackwootton** [comment]
Link is deprecated: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by qiwzhang** [comment]
Then you need to create a user-defined network, put both containers; esp and your backend; into that network.

Here is the instruction:

1) docker network create --driver bridge mmm
2) docker run -d --name=echo --net=mmm gcr.io/google-samples/echo-python:1.0
3) docker run --name=esp -d --net=mmm -p 80:8080 gcr.io/endpoints-release/endpoints-runtime:1 -s [SERVICE-NAME] -a echo:8080

We will update our doc:  https://cloud.google.com/endpoints/docs/openapi/get-started-compute-engine-docker

Thanks

**Comment by jackwootton** [comment]
Ah. So my Docker knowledge let me down here :)
I'll add some detail here in case anyone stumbles across this.

I incorrectly assumed because both containers were attached to the `bridge` network, this would be enough for ESP to forward to the gRPC server container. After following your instructions `docker network ls` yields:

```
NETWORK ID          NAME                DRIVER              SCOPE
560e907ecd1e        bridge              bridge              local               
884ba3f285e0        host                host                local               
1cceb6f3a694        mmm                 bridge              local               
04f9dca15f84        none                null                local

```

Thanks for updating the documentation too!

**Comment by jackwootton** [comment]
OK. I should have tested this on a Cloud Compute VM, because I've run into an issue. When following the documentation, [Running the sample API and ESP in a Docker container](https://cloud.google.com/endpoints/docs/grpc/get-started-grpc-compute-engine-docker#running_the_sample_api_and_esp_in_a_docker_container),  step 3 installed the Docker in the instance:

```
sudo apt-get update
sudo apt-get install docker.io
```
I check this worked with `apt --installed list | grep docker`, which yields:

`docker.io/jessie-backports,now 1.6.2~dfsg1-1~bpo8+1 amd64 [installed]`

However, according to a [topic on the Docker Forums](https://forums.docker.com/t/network-command-not-found/4716/2):

> The docker network command is supported in Docker 1.9.0 or later. You seem to be running Docker 1.7.1.

..which would explain why it works on my local machine but fails in the Cloud Compute VM with:

`docker: 'network' is not a docker command. See 'docker --help'.`

The VM instance has version 1.6 (`sudo docker -v`)

`Docker version 1.6.2, build 7c8fca2
`

I attempted to upgrade the package:

`sudo apt-get install --only-upgrade docker.io`

but it's already the latest:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker.io is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```

So it seems right now, working around --link with a new network is not an option on a live Cloud Compute VM?

**Comment by qiwzhang** [comment]
Thanks for pointing that out.  This section in the doc.  

sudo apt-get update
sudo apt-get install docker.io

 should be updated.  We should just ask users to following instructions at official docker website 

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

**Comment by jackwootton** [comment]
It seems Docker removed Jessie dist: https://download.docker.com/linux/ubuntu/dists/

```
Index of /linux/ubuntu/dists/
../
trusty/                                     2017-09-21 10:25  -
xenial/                                     2017-09-21 10:26  -
yakkety/                                    2017-09-21 10:27  -
zesty/                                      2017-09-21 10:28  -
```

I didn't select a specific dist, but it's what I got when following:  [Getting Started with gRPC on Compute Engine](https://cloud.google.com/endpoints/docs/grpc/get-started-grpc-compute-engine-docker#before-you-begin)

```
lsb_release -cs
jessie
```

**Comment by jackwootton** [comment]
I switched to Ubuntu xenial and was able to install Docker. Although users will have to cross check [supported Docker Ubuntu distros](https://download.docker.com/linux/ubuntu/dists/
) with available VM images.

The main issue is the Dockerfile uses the [Google Cloud Platform Python runtime](https://github.com/GoogleCloudPlatform/python-runtime) is based on Debian Jessie. So the Docker base image (gcr.io/google-appengine/python) for running applications on Google App Engine Flexible, Google Container Engine, or any other Docker host, doesn't have a corresponding Docker installation (i.e. Debian Jessie isn't supported by Docker). First line of the recommended Docker file is:

`FROM gcr.io/google_appengine/python`

 Just an FYI that right now, following [Getting Started with gRPC on Compute Engine](https://cloud.google.com/endpoints/docs/grpc/get-started-grpc-compute-engine-docker#before-you-begin) with having to install Docker (since `--link` [was deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)) will probably result in a lot of people finding the whole process pretty painful (IMO).

**Comment by qiwzhang** [comment]
Thanks,  I will request to update the doc about installing docker

**Comment by qiwzhang** [comment]
@jsonschema is it OK to close this issue?

**Comment by jackwootton** [comment]
Yes.
