### ISSUE TITLE
--service_config_url param not working.

### ISSUE THREAD

**Issue by ChrisTerBeke** [cloudendpoints/endpoints-tools#45]
Whenever I use a --service_config_url the container is not starting. I provide a valid OpenAPI 2.0 spec in JSON format on that URL, but the logs say there are errors in the service config. Any ideas?

**Comment by qiwzhang** [comment]
ESP expects service config generated by Google Servicemanagment component.  It doesn't support a raw OpenAPI spec. 

With a raw OpenAPI spec, you need to run

"gcloud endpoints services deploy openapi.yaml"

to deploy to Google ServiceManagement.  This is document here:  https://cloud.google.com/endpoints/docs/openapi/deploy-endpoints-config

@mangchiandjjoe could you help to either remove this flag.  It is not very useful.

**Comment by ChrisTerBeke** [comment]
Does Google Cloud do any special post-processing on the spec to make it work? I think being able to pass a remote config is still a useful feature, as not everyone runs the ESP container on Google Cloud.

**Comment by qiwzhang** [comment]
Cloud endpoints requires some Google services: Google ServieManagement and Google ServiceControl. Your ESP doesn't need to run on Google cloud platforms.  It can be run in any platforms, AWS or your private host.  As long as it has internet access to access Google services.

For service configs, it need to be deployed to "Google ServiceManagment" service, into its database.
