### ISSUE TITLE
Setting multiple values on --cors_allow_origin causes error on Chrome

### ISSUE THREAD

**Issue by ledmonster** [cloudendpoints/endpoints-tools#58]
Setting multiple values on --cors_allow_origin causes following error on Google Chrome.

```
Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000 http://localhost:3001', but only one is allowed. Origin 'http://localhost:3000' is therefore not allowed access.
```

It seems to be better to return only one 'Access-Control-Allow-Origin' from Nginx by dynamically checking `$http_origin`.

e.g. https://gist.github.com/alexjs/4165271

**Comment by ledmonster** [comment]
Also, it seems that we need 'Access-Control-Allow-Credentials' header, too.

**Comment by qiwzhang** [comment]
@lei-tang could you review this?

**Comment by lei-tang** [comment]
@qiwzhang Yes, I will review it.
