### ISSUE TITLE
Make the java client library compatible with the JPMS

### ISSUE THREAD

**Issue by Burtan** [cloudendpoints/endpoints-tools#71]
The generated library does not include any module-info.java file.
For reference: https://github.com/GoogleCloudPlatform/endpoints-framework-gradle-plugin/issues/94

**Comment by qiwzhang** [comment]
is this about endpoint frame-work?  if so, this is the wrong place.

hI @inklesspen, could you help?

**Comment by inklesspen** [comment]
Hi, @Burtan, the best way to get help with this problem is to visit the [google-cloud-endpoints Google group](https://groups.google.com/forum/#!forum/google-cloud-endpoints) and explain what steps you are following and what you expect to see happen.
